apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
spec:
  containers:
  - name: samplepod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
